import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./style.css";

export const metadata: Metadata = {
  title: "Ahmed Sherif Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link rel="shortcut icon" href="./assets/images/logo.ico" type="image/x-icon"/>
      <link rel="preconnect" href="https://fonts.googleapis.com"/>
      <link rel="preconnect" href="https://fonts.gstatic.com" />
      <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600&display=swap" rel="stylesheet"/>
      </head>
      <body>
        <main>
          <aside className="sidebar" data-sidebar>

            <div className="sidebar-info">

              <figure className="avatar-box">
                <img src="./assets/images/my-avatar.png" alt="Richard hanrick" width="80"/>
              </figure>

              <div className="info-content">
                <h1 className="name" title="Richard hanrick">Ahmed Sherif</h1>

                <p className="title">Web developer</p>
              </div>

              <button className="info_more-btn" data-sidebar-btn>
                Show Contacts
              </button>

            </div>

            <div className="sidebar-info_more">

              <div className="separator"></div>

              <ul className="contacts-list">

                <li className="contact-item">

                  <div className="contact-info">
                    <p className="contact-title">Email</p>

                    <a href="mailto:ahmmeedsherif.eng@gmail.com" className="contact-link">ahmmeedsherif.eng@gmail.com</a>
                  </div>

                </li>

                <li className="contact-item">


                  <div className="contact-info">
                    <p className="contact-title">Phone</p>

                    <a href="tel:+201090925023" className="contact-link">+20 1090925023</a>
                  </div>

                </li>

                <li className="contact-item">


                  <div className="contact-info">
                    <p className="contact-title">Birthday</p>

                    <time dateTime="2006-10-01">Oct. 1, 2006</time>
                  </div>

                </li>

                <li className="contact-item">

                  <div className="contact-info">
                    <p className="contact-title">Location</p>

                    <address>Mohandseen, Giza, Egypt</address>
                  </div>

                </li>

              </ul>

              <div className="separator"></div>
            </div>

          </aside>
          <div className="main-content">
            <nav className="navbar">

              <ul className="navbar-list">

                <li className="navbar-item">
                  <button className="navbar-link  active" data-nav-link>About</button>
                </li>

                <li className="navbar-item">
                  <button className="navbar-link" data-nav-link>Resume</button>
                </li>

                <li className="navbar-item">
                  <button className="navbar-link" data-nav-link>Portfolio</button>
                </li>

                <li className="navbar-item">
                  <button className="navbar-link" data-nav-link>Contact</button>
                </li>

              </ul>

            </nav>
            {children}
          </div>
        </main>
        <script src="./assets/js/script.js"></script>
      </body>
    </html>
  );
}
